# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: a_bot
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - a_bot_shoulder_pan_joint
    - a_bot_shoulder_lift_joint
    - a_bot_elbow_joint
    - a_bot_wrist_1_joint
    - a_bot_wrist_2_joint
    - a_bot_wrist_3_joint
    - a_bot_finger_joint
    - b_bot_shoulder_pan_joint
    - b_bot_shoulder_lift_joint
    - b_bot_elbow_joint
    - b_bot_wrist_1_joint
    - b_bot_wrist_2_joint
    - b_bot_wrist_3_joint
    - b_bot_finger_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: /a_bot/scaled_pos_joint_traj_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - a_bot_shoulder_pan_joint
      - a_bot_shoulder_lift_joint
      - a_bot_elbow_joint
      - a_bot_wrist_1_joint
      - a_bot_wrist_2_joint
      - a_bot_wrist_3_joint
  - name: /b_bot/scaled_pos_joint_traj_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - b_bot_shoulder_pan_joint
      - b_bot_shoulder_lift_joint
      - b_bot_elbow_joint
      - b_bot_wrist_1_joint
      - b_bot_wrist_2_joint
      - b_bot_wrist_3_joint
a_bot/gripper_controller:
  type: GripperCommand
  joints:
    a_bot_finger_joint
  gains:
    a_bot_finger_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
b_bot/gripper_controller:
  type: GripperCommand
  joints:
    b_bot_finger_joint
  gains:
    b_bot_finger_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
