# Based on https://packaging.python.org/guides/supporting-windows-using-appveyor/
version: '{branch}-{build}'
build: 'off'
cache:
  - '%LOCALAPPDATA%\pip\Cache'
environment:
  TOXENV: 'py'
  matrix:
      # Specifically use py27 env to get custom deps
    - PYTHON: 'C:\Python27'
      TOXENV: 'py27'
    - PYTHON: 'C:\Python27-x64'
      TOXENV: 'py27'
    - PYTHON: 'C:\Python34'
    - PYTHON: 'C:\Python34-x64'
    - PYTHON: 'C:\Python35'
    - PYTHON: 'C:\Python35-x64'
    - PYTHON: 'C:\Python36'
    - PYTHON: 'C:\Python36-x64'
    - PYTHON: 'C:\Python27'
      TOXENV: 'py27-check'
    - PYTHON: 'C:\Python36'
      TOXENV: 'py36-check'
init:
  - ps: 'echo $env:TOXENV'
  - ps: 'ls C:\Python*'
install:
  - '%PYTHON%\Scripts\pip install setuptools>=18.0.1 wheel tox virtualenv>=13.1.0 coverage'
  - '%PYTHON%\Scripts\virtualenv --version'
  - '%PYTHON%\Scripts\easy_install --version'
  - '%PYTHON%\Scripts\pip --version'
  - '%PYTHON%\Scripts\tox --version'
test_script:
  - '%PYTHON%\Scripts\tox -v'
on_failure:
  - ps: 'dir env:'
  - ps: 'get-content .tox\*\log\*'
on_success:
  - '%PYTHON%\Scripts\tox -e codecov'
artifacts:
  - path: 'dist\*'

### To enable remote debugging uncomment this (also, see: http://www.appveyor.com/docs/how-to/rdp-to-build-worker):
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
