#!/usr/bin/env python

import sys
import unittest

import rospy

from natnet_ros import RosLogger


class LogTest(unittest.TestCase):

    def __init__(self, *args):
        super(LogTest, self).__init__(*args)
        rospy.init_node("logtest", log_level=rospy.DEBUG)

    def setUp(self):
        self.logger = RosLogger()

    def test_debug(self):
        self.logger.debug("test %i", 1)

    def test_info(self):
        self.logger.info("test %i", 2)

    def test_warning(self):
        self.logger.warning("test %i", 3)

    def test_error(self):
        self.logger.error("test %i", 4)

    def test_fatal(self):
        self.logger.fatal("test %i", 5)


if __name__ == '__main__':
    import rostest
    rostest.run('natnet_ros', 'logtest', LogTest, sys.argv)
