#!/usr/bin/env python
# coding: utf-8
"""NatNet client ROS node.

Copyright (c) 2017, Matthew Edwards.  This file is subject to the 3-clause BSD
license, as found in the LICENSE file in the top-level directory of this
distribution and at https://github.com/mje-nz/natnet_ros/blob/master/LICENSE.
No part of natnet_ros, including this file, may be copied, modified,
propagated, or distributed except according to the terms contained in the
LICENSE file."""


import rospy

from natnet_ros import NatnetClientNode


if __name__ == '__main__':
    rospy.init_node('mocap', disable_signals=True)
    if rospy.get_param('~debug', None):
        # Can't get parameters until init_node, and the only official way to set the ROS logger level is using
        # init_node, so just hack it
        import logging
        logging.getLogger('rosout').setLevel(logging.DEBUG)
        log_level = rospy.DEBUG
        rospy.logdebug('Debug logging enabled')
    try:
        node = NatnetClientNode()
        node.run()
    finally:
        # TODO: Handle ROS shutdown properly
        rospy.signal_shutdown(reason='Finished')
