<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
       name="diabolo_base_scene" >
  <!-- This is the main file defining our robot arrangement and physical environment. -->

  <!-- Calibration parameters -->
  <xacro:property name="bots_x" value="-0.0"/>
  <xacro:property name="bots_z" value="0.75"/>

  <xacro:property name="a_bot_x" value="-0.004"/>
  <xacro:property name="a_bot_y" value="-0.525"/>
  <xacro:property name="a_bot_theta" value="0.0"/>
  <xacro:property name="b_bot_x" value="-0.0"/>
  <xacro:property name="b_bot_y" value="0.525"/>
  <xacro:property name="b_bot_theta" value="-3.141"/>

  <!-- common stuff -->
  <xacro:include filename="$(find ur_description)/urdf/common.gazebo.xacro" />

  <!-- robots -->
  <xacro:include filename="$(find ur_e_description)/urdf/ur5e.urdf.xacro" />
  
  <xacro:include filename="$(find diabolo_scene_description)/urdf/osx_environment.xacro" />
  
  <!-- Robot bases -->
  <!-- Putting these at height 0.0 makes them intersect with the ground, so they are elevated. -->
  <!-- There are some instabilities in Gazebo when the box is big, for some reason. -->
  <xacro:include filename="$(find diabolo_scene_description)/urdf/components/o2ac_base.xacro" />
  <xacro:o2ac_base boxname="a_bot_base_smfl" parent="diabolo_ground">
    <origin xyz="${a_bot_x-.65/2} ${a_bot_y-.65/2} ${bots_z-.05}" rpy="0 0 0" />
  </xacro:o2ac_base>
  <xacro:o2ac_base boxname="b_bot_base_smfl" parent="diabolo_ground">
    <origin xyz="${b_bot_x-.65/2} ${b_bot_y-.65/2} ${bots_z-.05}" rpy="0 0 0" />
  </xacro:o2ac_base>
  
  <!-- Main workspace -->
  <xacro:include filename="$(find diabolo_scene_description)/urdf/components/o2ac_box.xacro" />
  <xacro:property name="workplate_w" value="0.65"/>
  <xacro:property name="workplate_l" value="0.4"/>
  <xacro:property name="workplate_h" value="0.02"/>
  <xacro:property name="robot_mount_plate" value="0.005"/>  <!-- The plate holding the robots, resting on the alu frames -->
  <xacro:o2ac_box boxname="workplate" box_w="${workplate_w}" box_l="${workplate_l}" box_h="${workplate_h}" parent="diabolo_ground">
    <origin xyz="${-workplate_w/2+bots_x} ${-(workplate_l/2)} ${bots_z-robot_mount_plate}" rpy="0 0 0" />   
  </xacro:o2ac_box>
  <link name="workspace_center" />
  <joint name="world_to_workspace" type="fixed">
    <parent link="diabolo_ground" />
    <child link="workspace_center" />
    <origin xyz="${bots_x} 0.0 ${bots_z-robot_mount_plate+workplate_h}" rpy="0.0 0.0 0.0" />
  </joint>

  <xacro:ur5e_robot prefix="a_bot_" joint_limited="true"
    shoulder_pan_lower_limit="${-3*pi/2}" shoulder_pan_upper_limit="${3*pi/2}"
    shoulder_lift_lower_limit="${-2*pi}" shoulder_lift_upper_limit="0.0"
    elbow_joint_lower_limit="${-pi}" elbow_joint_upper_limit="0.0"
    wrist_1_lower_limit="${-2*pi}" wrist_1_upper_limit="0.0"
    wrist_2_lower_limit="${-2*pi}" wrist_2_upper_limit="${2*pi}"
    wrist_3_lower_limit="${-2*pi}" wrist_3_upper_limit="${2*pi}"
    transmission_hw_interface="hardware_interface/PositionJointInterface"
    safety_limits="false" safety_pos_margin="0.15"
    safety_k_position="20"
    kinematics_file="${load_yaml('$(find diabolo_scene_description)/config/a_bot_calibration.yaml')}"
  />

  <xacro:ur5e_robot prefix="b_bot_" joint_limited="true"
    shoulder_pan_lower_limit="${-3*pi/2}" shoulder_pan_upper_limit="${3*pi/2}"
    shoulder_lift_lower_limit="${-pi}" shoulder_lift_upper_limit="${pi}"
    elbow_joint_lower_limit="0.0" elbow_joint_upper_limit="${pi}"
    wrist_1_lower_limit="${-pi}" wrist_1_upper_limit="${pi}"
    wrist_2_lower_limit="${-2*pi}" wrist_2_upper_limit="${2*pi}"
    wrist_3_lower_limit="${-2*pi}" wrist_3_upper_limit="${2*pi}"
    kinematics_file="${load_yaml('$(find diabolo_scene_description)/config/b_bot_calibration.yaml')}"
  />

  <joint name="world_a_bot_joint" type="fixed">
    <parent link="diabolo_ground" />
    <child link="a_bot_base_link" />
    <origin xyz="${a_bot_x} ${a_bot_y} ${bots_z}" rpy="0.0 0.0 ${a_bot_theta}" />
  </joint>

  <joint name="world_b_bot_joint" type="fixed">
    <parent link="diabolo_ground" />
    <child link = "b_bot_base_link" />
    <origin xyz="${b_bot_x} ${b_bot_y} ${bots_z}" rpy="0.0 0.0 ${b_bot_theta}" />
  </joint>

  <!-- spawn and attach robotiq 85 gripper + diabolo attachments ...) -->
  <xacro:include filename="$(find diabolo_scene_description)/urdf/components/diabolo_end_effector.urdf.xacro" />
  <xacro:diabolo_end_effector prefix="a_bot_" use_soft_wrist="false" use_cameras="false" parent = "a_bot_ee_link" />
  
  <xacro:include filename="$(find diabolo_scene_description)/urdf/components/diabolo_end_effector.urdf.xacro" />
  <xacro:diabolo_end_effector prefix="b_bot_" use_soft_wrist="false" use_cameras="false" parent = "b_bot_ee_link" />
  

  <!-- Diabolo stick tip joints -->
  <!-- Measured via the UR teach pendant TCP wizard -->
  <joint name="a_bot_diabolo_tip_joint" type="fixed">
    <parent link="a_bot_ee_link"/>
    <child link="a_bot_diabolo_stick_tip"/>
    <origin rpy="0 0 0" xyz="0.356 -0.0055 0.043"/>
  </joint>
  <link name="a_bot_diabolo_stick_tip"/>

  <joint name="b_bot_diabolo_tip_joint" type="fixed">
    <parent link="b_bot_ee_link"/>
    <child link="b_bot_diabolo_stick_tip"/>
    <origin rpy="0 0 0" xyz="0.355 -.0035 0.048"/>
  </joint>
  <link name="b_bot_diabolo_stick_tip"/>

  <!-- Add cameras -->
  <xacro:include filename="$(find diabolo_scene_description)/urdf/components/_d435.urdf.xacro" />

  <link name="diabolo_bottom_camera_holder_link" />
  <joint name="diabolo_bottom_camera_holder_joint" type="fixed">
    <parent link="workspace_center" />
    <child  link="diabolo_bottom_camera_holder_link" />
    <origin xyz=".33 0 -0.74" rpy="${pi} ${-pi*69/180.0} 0" />
  </joint>
  <!-- <xacro:o2ac_sensor_d435 prefix="diabolo_bottom_" parent="diabolo_bottom_camera_holder_link" use_nominal_extrinsics="true">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:o2ac_sensor_d435> -->

  <!-- FAKE CALIBRATED FRAME -->
  <!-- <link name="calibrated_diabolo_bottom_camera_depth_optical_frame" />
  <joint name="fake_diabolo_bottom_depth_calib_joint" type="fixed">
    <parent link="diabolo_bottom_camera_depth_optical_frame" />
    <child  link="calibrated_diabolo_bottom_camera_depth_optical_frame" />
    <origin xyz="0 0 0" rpy="0 0 0" />
  </joint> -->
  
  <!-- The "world" link definition should be removed, but apparently it is necessary for Gazebo -->
  <link name="world" />
  <joint name="world_diabolo_joint" type="fixed">
    <parent link="world" />
    <child link="diabolo_ground" />
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
  </joint>
  <link name="diabolo_ground" />

  <link name="mocap" />
  <joint name="workspace_to_mocap_joint" type="fixed">
    <parent link="workspace_center" />
    <child link="mocap" />
    <!-- <origin xyz="0.05 0.0 0.0" rpy="0.0 0.0 ${-pi/2}" /> -->
    <!-- <origin xyz="0.05 0.0 0.0" rpy="${-pi/2} ${pi/2} 0" /> -->
    <!-- <origin xyz="0.05 0.0 0.0" rpy="${pi/2} 0 ${pi/2}" /> -->
    <origin xyz="0.04 0.01 0.0" rpy="${-pi/2} 0 ${-pi/2}" />
  </joint>
  <!-- See http://46.101.206.60/rotate -->
  
 
</robot>

<!-- 
x' = z 
z' = -y
y' = -x -->
